In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [51]:
df=pd.read_csv(r"C:\Users\agata\Downloads\marketing_customer_analysis_clean.csv")

In [52]:
df.head()

unnamed:_0 customer       state  customer_lifetime_value response  \
0           0  DK49336     Arizona              4809.216960       No   
1           1  KX64629  California              2228.525238       No   
2           2  LZ68649  Washington             14947.917300       No   
3           3  XL78013      Oregon             22332.439460      Yes   
4           4  QA50777      Oregon              9025.067525       No   

   coverage education effective_to_date employmentstatus gender  ...  \
0     Basic   College        2011-02-18         Employed      M  ...   
1     Basic   College        2011-01-18       Unemployed      F  ...   
2     Basic  Bachelor        2011-02-10         Employed      M  ...   
3  Extended   College        2011-01-11         Employed      M  ...   
4   Premium  Bachelor        2011-01-17    Medical Leave      F  ...   

   number_of_policies     policy_type        policy  renew_offer_type  \
0                   9  Corporate Auto  Corporate L3            Offer3   
1                   1   Personal Auto   Personal L3            Offer4   
2                   2   Personal Auto   Personal L3            Offer3   
3                   2  Corporate Auto  Corporate L3            Offer2   
4                   7   Personal Auto   Personal L2            Offer1   

   sales_channel  total_claim_amount  vehicle_class  vehicle_size  \
0          Agent          292.800000  Four-Door Car       Medsize   
1    Call Center          744.924331  Four-Door Car       Medsize   
2    Call Center          480.000000            SUV       Medsize   
3         Branch          484.013411  Four-Door Car       Medsize   
4         Branch          707.925645  Four-Door Car       Medsize   

  vehicle_type month  
0            A     2  
1            A     1  
2            A     2  
3            A     1  
4            A     1  

[5 rows x 27 columns]

In [53]:
df=df.select_dtypes(include="number")

In [127]:
y=df[["total_claim_amount"]]

In [128]:
y

total_claim_amount
0              292.800000
1              744.924331
2              480.000000
3              484.013411
4              707.925645
...                   ...
10905         1214.400000
10906          273.018929
10907          381.306996
10908          618.288849
10909         1021.719397

[10910 rows x 1 columns]

In [107]:
X=df.drop("total_claim_amount", axis=1)

In [108]:
X

unnamed:_0  customer_lifetime_value  income  monthly_premium_auto  \
0               0              4809.216960   48029                    61   
1               1              2228.525238       0                    64   
2               2             14947.917300   22139                   100   
3               3             22332.439460   49078                    97   
4               4              9025.067525   23675                   117   
...           ...                      ...     ...                   ...   
10905       10905             15563.369440       0                   253   
10906       10906              5259.444853   61146                    65   
10907       10907             23893.304100   39837                   201   
10908       10908             11971.977650   64195                   158   
10909       10909              6857.519928       0                   101   

       months_since_last_claim  months_since_policy_inception  \
0                     7.000000                             52   
1                     3.000000                             26   
2                    34.000000                             31   
3                    10.000000                              3   
4                    15.149071                             31   
...                        ...                            ...   
10905                15.149071                             40   
10906                 7.000000                             68   
10907                11.000000                             63   
10908                 0.000000                             27   
10909                31.000000                              1   

       number_of_open_complaints  number_of_policies  month  
0                       0.000000                   9      2  
1                       0.000000                   1      1  
2                       0.000000                   2      2  
3                       0.000000                   2      1  
4                       0.384256                   7      1  
...                          ...                 ...    ...  
10905                   0.384256                   7      1  
10906                   0.000000                   6      1  
10907                   0.000000                   2      2  
10908                   4.000000                   6      2  
10909                   0.000000                   3      1  

[10910 rows x 9 columns]

In [102]:
X

array([[0.00000000e+00],
       [4.80921696e+03],
       [4.80290000e+04],
       ...,
       [0.00000000e+00],
       [3.00000000e+00],
       [1.00000000e+00]])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
from sklearn.linear_model import LinearRegression

In [147]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=42)

In [133]:
X_train

unnamed:_0  customer_lifetime_value  income  monthly_premium_auto  \
7722        7722              2903.939763   67763                    73   
6888        6888              7317.014254   24083                    63   
675          675              5568.889245   53295                    70   
4098        4098              3451.102440       0                   104   
4518        4518              2402.172069   43246                    62   
...          ...                      ...     ...                   ...   
5734        5734              3810.238281       0                   108   
5191        5191              3815.851163   38651                    98   
5390        5390              7850.590399       0                    69   
860          860              4974.235309       0                    70   
7270        7270             38055.209530       0                   115   

      months_since_last_claim  months_since_policy_inception  \
7722                     17.0                             69   
6888                     22.0                              2   
675                      12.0                             97   
4098                     19.0                             65   
4518                     19.0                             89   
...                       ...                            ...   
5734                      7.0                             57   
5191                     12.0                             83   
5390                      5.0                             78   
860                      18.0                             74   
7270                     21.0                             78   

      number_of_open_complaints  number_of_policies  month  
7722                        1.0                   1      1  
6888                        1.0                   2      1  
675                         0.0                   8      1  
4098                        2.0                   1      1  
4518                        0.0                   1      2  
...                         ...                 ...    ...  
5734                        0.0                   1      2  
5191                        0.0                   1      1  
5390                        0.0                   2      2  
860                         0.0                   3      2  
7270                        0.0                   2      2  

[7637 rows x 9 columns]

In [134]:
y_train

total_claim_amount
7722           59.861963
6888          340.453606
675           250.423844
4098          499.200000
4518           52.435202
...                  ...
5734          777.600000
5191          470.400000
5390          331.200000
860           336.000000
7270          552.000000

[7637 rows x 1 columns]

In [17]:
from sklearn.preprocessing import StandardScaler

In [12]:
scale= StandardScaler()

In [148]:
scale.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [149]:
transformed_train_X=scale.transform(X_train)

(7637, 9)

In [19]:
lm=LinearRegression()

In [150]:
model=lm.fit(transformed_train_X, y_train)

In [151]:
model.coef_

array([[  1.89711627,  -4.88084046, -99.91757533, 188.04026999,
          2.764124  ,  -4.65570423,  -1.14006818,  -0.24668876,
         -0.32341426]])

In [152]:
model.intercept_

array([435.43080381])

In [153]:
transformed_test_X=scale.transform(X_test)

In [155]:
y_pred=model.predict(transformed_test_X)

In [161]:
y_test

total_claim_amount
4829           475.423848
5081           350.400000
5011           482.400000
4625           673.342650
3838           302.400000
...                   ...
9968           144.728404
5239            93.566940
10001          253.637853
4828           284.000172
10483          485.183645

[3273 rows x 1 columns]

In [191]:
y_pred[:,0]

array([125.51860824, 351.47534057, 419.23245276, ..., 413.44484161,
       187.28861341, 425.0999335 ])

In [157]:
from sklearn.metrics import mean_squared_error as mse

In [159]:
mse(y_test, y_pred)**0.5

199.52115732228904

In [182]:
real_vs_pred = pd.DataFrame({'y_test': y_test["total_claim_amount"], 'y_pred':y_pred[:,0]})

In [184]:
real_vs_pred

y_test      y_pred
4829   475.423848  125.518608
5081   350.400000  351.475341
5011   482.400000  419.232453
4625   673.342650  433.127283
3838   302.400000  155.341392
...           ...         ...
9968   144.728404  332.692517
5239    93.566940  743.404324
10001  253.637853  413.444842
4828   284.000172  187.288613
10483  485.183645  425.099933

[3273 rows x 2 columns]